### ISSUE TITLE
How make diffrent color of points?

### ISSUE THREAD

**Issue by chiddekel** [flekschas/regl-scatterplot#102]
How to make this code correct that produces two types of colors of points?
(HINT the code provide necessary ones and zeros.)

  let sourceOfPoints = points.map((d) => {
    (d[1] === 0) ? d[3] = [1, 1, 1, 1] : d[3] = [1, 0.5, 0, 1];
    return d;
  });

  scatterplot.set({
    pointColor: sourceOfPoints.map((d) => d[3]),
  })

**Comment by flekschas** [comment]
See https://github.com/flekschas/regl-scatterplot#color-opacity-and-size-encoding on how to color points. You don't pass RGBAs. You say which dimension of your data defines the color. (either `valueA` or `valueB` depending on whether the third or fourth dimension of your points contains the value you want to color encode)

**Comment by flekschas** [comment]
Closing this issue now as the docs provide an answer
