### ISSUE TITLE
Background image redraw issue

### ISSUE THREAD

**Issue by plankter** [flekschas/regl-scatterplot#11]
Initial view after component is mounted:

![image](https://user-images.githubusercontent.com/1336618/81055161-6fe36b80-8ec8-11ea-981a-9e3d3db41586.png)

After zooming, panning or even focus change visualization with background image is corrupted.

![image](https://user-images.githubusercontent.com/1336618/81054877-e3d14400-8ec7-11ea-8b39-9b711a7aac2f.png)

**Comment by flekschas** [comment]
Thanks for reporting. Do you have a live example? You could fork https://observablehq.com/@flekschas/regl-scatterplot for example.

**Comment by flekschas** [comment]
I created a quick demo at https://observablehq.com/@flekschas/regl-scatterplot-with-a-background-image

**Comment by flekschas** [comment]
The build-in example works as expected.

**Comment by plankter** [comment]
Thank you for the fast response. I still have the same problem.

Here is how demo looks like in Firefox:

![image](https://user-images.githubusercontent.com/1336618/81073222-99f85600-8ee7-11ea-845c-b71ca396b907.png)

And this is in Chrome:

![image](https://user-images.githubusercontent.com/1336618/81073282-b3010700-8ee7-11ea-8333-f37fa1d38778.png)

I am using Ubuntu 19.10 at the moment, with NVidia card. Probably it is not an issue on other platforms.

**Comment by flekschas** [comment]
I can reproduce the issue with the live example. What's strange is that it works when I use the local example:

1. `npm run start`
2. `http://localhost:8081/texture-background.html`

It might be an issue with the GL extensive. I'll investigate!

**Comment by flekschas** [comment]
Meanwhile, if you have the chance, can you test the local version as well?

All you have to do is:

```
git clone https://github.com/flekschas/regl-scatterplot/
cd regl-scatterplot
npm install
npm run start
```

Then open [http://localhost:8081/texture-background.html](http://localhost:8081/texture-background.html)

**Comment by flekschas** [comment]
Okay, the Observables demo is slightly funky. I am not sure we can use that for debugging. When I execute a certain cell twice the image remains but the points are messed up. regl-scatterplot might just not be compatible with Observables at this point.

![May-05-2020 11-15-31](https://user-images.githubusercontent.com/932103/81082838-cf8a4880-8ec1-11ea-90f3-f0bee99696d1.gif)

When you test `http://localhost:8081/texture-background.html` do you see any error messages in the web dev console?

**Comment by plankter** [comment]
I tested it locally, and everything is working properly. Zoom, rotation, selections works fine without any error messages in the console. Strange.

**Comment by flekschas** [comment]
In which environment did you originally spot the issue?

**Comment by plankter** [comment]
I am using it in Vue app, via `vue-cli-service serve` command (which is a wrapper above Webpack dev server). I tried to use source code directly, as I had a suspicion this was a Rollup issue, but it didn't help.

**Comment by flekschas** [comment]
Could you do me a favor and test the master code in your Vue app too? I wonder if somehow the build got messed up.

To test the master you can do:

```
cd regl-scatterplot
npm run build
npm link
cd ../path/to/your/vue/app
npm link regl-scatterplot
vue-cli-service serve
```

**Comment by plankter** [comment]
Sure. I think more or less i did it already: copied the source code from "src" folder directly into my app source code subfolder and install all `regl-scatterplot` dependencies, including peer ones. But I'll check it again.

**Comment by plankter** [comment]
I repeated the steps you suggested, but unfortunately nothing has changed: same issues, no error messages in console.

**Comment by flekschas** [comment]
Thanks for testing! Do you think you could share a simple example of your Vue app? A jsfiddle would be best.

**Comment by plankter** [comment]
Sure, I'll try to prepare it tomorrow.

**Comment by plankter** [comment]
I created a demo repository at: https://github.com/plankter/regl-scatterplot-demo
Sorry, i didn't understand how to make a proper Vue + TypeScript environment on jsfiddle.

Just run `yarn install` and `yarn run serve`. `npm install` and `npm run serve` should work too.

**Comment by flekschas** [comment]
Awesome, thanks a lot! I'll take a look.

**Comment by flekschas** [comment]
Found the issue :)

You need to use the same `regl` instance in the scatterplot as well:

```javascript
this.scatterplot = createScatterplot({
  regl,  // This line fixes the issue!
  canvas,
  width,
  height,
  opacity: 1,
  pointSize: 2,
  pointSizeSelected: 1,
  pointOutlineWidth: 1,
  lassoMinDelay: 15,
  backgroundImage: backgroundImage,
});
```

**Comment by plankter** [comment]
Works now, thanks a lot!

**Comment by flekschas** [comment]
Great! And sorry for the hassle. I am thinking the whole code of creating a texture should be internalized. It seems unnecessarily complicated to have to create a texture first. Anyway, that's future work :)
