### ISSUE TITLE
nit: Duplicate peer-dependencies

### ISSUE THREAD

**Issue by insertmike** [flekschas/regl-scatterplot#128]
nit: New versions of NPM handle peer dependencies IIRC. In this case, they do not need to be installed explicitly:

In `README.MD`: 

```
_FYI, regl-scatterplot doesn't bundle regl and pub-sub-es, which is why you have to install them separately._
```

This could lead to some locked version of `pub-es` or `regl` that mismatch with regl-scatter.

**Comment by insertmike** [comment]
@flekschas 

As of npm version 7 (2021), peer dependencies are installed automatically when you a project to your `package.json`. This means that they do not longer need to be added explicitly anymore. 

[NPM Doc Ref](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies)

On the other side, that would be a pity to debug if someone tries to install and experience some issues because of his old NPM version. And we might need to note this at the README which makes the removing of the peer-dependency comment not so useful.

What I meant however about the 'locked version' is that we may encounter the following scenario:

Someone with old version of node installs `pubsub-es` explicitly. A new version of `regl-scatter` comes up which relies on a breaking change in `pubsub-es`. If this version is locked in either the package manager lock file as the old one (not explicitly as latest, this would essentially break the project using the library.

**Comment by insertmike** [comment]
Actually, @flekschas , looking at the `package.json` I see that `pub-sub-es` and `regl` are both added as peer-dependencies as well as dependencies. Why is that? If this is the case, why would we need to explicitly tell people to install them?

**Comment by flekschas** [comment]
In order to locally test regl-scatterplot you need the two libraries. However during bundling they are excluded. See https://github.com/flekschas/regl-scatterplot/blob/master/rollup.config.mjs#L22-L25

**Comment by flekschas** [comment]
Closing this issue now for the reasons explained in #130 (https://github.com/flekschas/regl-scatterplot/pull/130#issuecomment-1604349710)

Happy to reopen it if I missed something.
