### ISSUE TITLE
Background image is horizontally flipped.

### ISSUE THREAD

**Issue by plankter** [flekschas/regl-scatterplot#13]
Background image visualization is horizontally flipped comparing to original image.

**Comment by flekschas** [comment]
Thanks for reporting. I fixed the bug and will release a new version today or tomorrow once I got #12 fixed as well.

**Comment by flekschas** [comment]
Sorry for the delay, the issue is fixed in `v0.8`. Note that I've also refactored the `colors` property.

**Comment by plankter** [comment]
Thank you!
