### ISSUE TITLE
`lassoEnd` with no point in selection does not publish deselect event

### ISSUE THREAD

**Issue by insertmike** [flekschas/regl-scatterplot#132]
After selecting an empty region with the lasso, the `select` event is always triggered, with 0 points array:

```
  const select = (pointIdxs, { merge = false, preventEvent = false } = {}) => {
 ```

Internally, the function clears the `selectionPoints` state and triggers the `deselect` method:

```
selectedPoints = pointIdxsArr;
if (currSelectedPoints.length > 0 && selectedPoints.length === 0) {
   deselect({ preventEvent });
   return;
}
```

In the `deselect` method, the `lassoClearEvent` checks goes through, which clears the lasso, but since the `selectedPoints` array have been updated in the `select` method to have a length of 0, the `pubSub.publish('deslect')` event is never triggered.

```
  const deselect = ({ preventEvent = false } = {}) => {
    if (lassoClearEvent === LASSO_CLEAR_ON_DESELECT) lassoClear();
    if (selectedPoints.length) {
      if (!preventEvent) pubSub.publish('deselect');
      selectedPointsConnectionSet.clear();
      setPointConnectionColorState(selectedPoints, 0);
      selectedPoints = [];
      selectedPointsSet.clear();
      draw = true;
    }
  };
```

Creating a PR now.

**Comment by flekschas** [comment]
> After selecting an empty region with the lasso, the `select` event is always triggered, with 0 points array:

This is not true. Selecting an empty region does not trigger a `select` event because of https://github.com/flekschas/regl-scatterplot/blob/master/src/index.js#L704-L707.

But I think I know what mean. After having select some number of points and then lassoing to select no points will clear the selection but does not trigger a `deselect` event.

**Comment by flekschas** [comment]
Closing this as #133 is merged
