### ISSUE TITLE
`aspectRatio` is missing from Typescript declarations

### ISSUE THREAD

**Issue by funmaker** [flekschas/regl-scatterplot#146]
- [x] Check for duplicate issues.
- [x] Describe the bug: what did you do to trigger it, what was your expected behavior, and what did you experience instead.
- [x] Use the latest versions of `regl-scatterplot`.
- [x] Provide an [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [x] If applicable, include error messages, screenshots, GIFs, videos, or working examples.

Hi.

`aspectRatio` is missing from `types.d.ts`, trying to specify it in `createScatterplot` or `scatterplot.set` throws typescript errors.

Reproduction:
```ts
createScatterplot({
  canvas,
  width: canvas.clientWidth,
  height: canvas.clientHeight,
  aspectRatio: 1.0,
});
```
Error:
```
(Type) is not assignable to parameter of type  Partial<Properties> 
Object literal may only specify known properties, and  aspectRatio  does not exist in type  Partial<Properties>
```

Also there is a typo in README.md:
> // default it is assumed that your data **us** following a 1:1 ratio and this ratio

**Comment by flekschas** [comment]
Turns out what you're trying to do isn't yet supported. So it's technically not a missing TS declaration.

At the moment you have to do `scatterplot.set({ aspectRatio: 1.337 })`

**Comment by funmaker** [comment]
@flekschas this also doesn't work, aspectRatio is missing from Settable type, which scatterplot.set expects. In fact, there is no mention of `aspectRatio` anywhere in types.d.ts

```
TS2345: Argument of type  { aspectRatio: number; }  is not assignable to parameter of type  Partial<Settable> 
Object literal may only specify known properties, and  aspectRatio  does not exist in type  Partial<Settable>
```

Another discrepancy in types is that `opacity` parameter doesn't accept `number[]`, even though it does work and is used in an example in readme.

**Comment by flekschas** [comment]
I know that the type isn't defined. What I was trying to say is that technically and irrespectively of type hints, `createScatterplot({ aspectRatio: 1.377 });` is not implemented yet.

**Comment by flekschas** [comment]
This PR should fix all three issues: https://github.com/flekschas/regl-scatterplot/pull/147. Let me know if it looks good and I'll merge it and release a new version

**Comment by funmaker** [comment]
LGTM 👍
Thanks
