### ISSUE TITLE
Centering plot view

### ISSUE THREAD

**Issue by plankter** [flekschas/regl-scatterplot#15]
Changing `target` parameter from the initial [0, 0] value doesn't affect anything. In my case problem is that (0, 0) point isn't located at the center of the scatterplot component, but shifted to bottom right corner (see screenshot), and i would like to shift the view so the plot is centered.

I don't know if you can see it on the uploaded screenshot, but a selected point, which is located relatively in the center of the screen, has coordinates [X: -0.5
Y: 0.10666394233703613]. But probably i am missing something here.

![Screenshot from 2020-05-28 16-21-17](https://user-images.githubusercontent.com/1336618/83160217-3688cf00-a107-11ea-812f-bdbc739304d8.png)

**Comment by flekschas** [comment]
I can confirm. It's a bug :) Working on a fix now

**Comment by flekschas** [comment]
Found the issue. Should be easy to fix

**Comment by flekschas** [comment]
Fixed. Will add a test before pushing a new version.

**Comment by flekschas** [comment]
If you have the chance, can you test the master version? Locally I can now set an initial `cameraTarget`, `cameraDistance`, and `cameraRotation`. (Note, I renamed the properties for clarity). You can also now update the camera position programmatically via the `set` method (e.g., `set({ cameraTarget: [1, 1] })`). If it works for you as well, I'll release a new version

**Comment by plankter** [comment]
Thank you, i tested master version and it works now.

**Comment by flekschas** [comment]
The fix is now released in v0.9. Thanks again for reporting :)
