### ISSUE TITLE
Tooltips for each point in the plot

### ISSUE THREAD

**Issue by masalinas** [flekschas/regl-scatterplot#156]
Add tooltips for each point in the plot

**Comment by masalinas** [comment]
Right now I tryed to resolve using this piece of code:

 ```
scatterplot.subscribe("pointOver", (point) => {
      this.pointHover = this.dataset[point];

      console.log(this.pointHover);      
 
      this.pointPosition = scatterplot.getScreenPosition(point)

      this.tooltip.nativeElement.style.visibility = 'visible';
      this.tooltip.nativeElement.style.position = 'absolute';
      this.tooltip.nativeElement.style.left = this.pointPosition[0] + 170 + "px";
      this.tooltip.nativeElement.style.top = this.pointPosition[1] + 10 + "px";
    }); 

    scatterplot.subscribe("pointOut", (point) => {
      this.tooltip.nativeElement.style.visibility = 'hidden';
    }); 
```

I have a problem positioning the tooltip as you see, setting this value for a particular resolution, so I ahve this problem. Exist other way to set the location of the tooltip relative to the canvas?

**Comment by flekschas** [comment]
Not sure what you mean with "tooltip for **each** point" but you can easily implement tooltips with your favorite UI library using [`scatterplot.subscribe('pointover', pointoverHandler);`, `scatterplot.subscribe('pointout', pointoutHandler);`](https://github.com/flekschas/regl-scatterplot#events), and [`const [x, y] = scatterplot.getScreenPosition(pointIdx);`](https://github.com/flekschas/regl-scatterplot#scatterplot.getScreenPosition)

**Comment by flekschas** [comment]
The screen position is relative to canvas element. So depending on your setup you might need to do something like `const { top, left } = scatterplot.get('canvas').getBoundingClientRect()` and subtract the scroll offset from `top` and `left`.

**Comment by masalinas** [comment]
Ok grate with the piece of code: `const { top, left } = scatterplot.get('canvas').getBoundingClientRect()` i can recover this ofset and apply to my tooltip to be adapted to any resolution, thanks
