### ISSUE TITLE
Selection handlers are called in case of two plot instances

### ISSUE THREAD

**Issue by plankter** [flekschas/regl-scatterplot#16]
I've encountered a very awkward behavior of the component: there are two separate regl-scatterplot instances, both have their own selection handlers. 

Both selection handlers are called when lasso tool is used, but when single point selected without holding `Shift` button, then it works properly - only one selection handler is called. Seems like a bug in lasso implementation that share the state between instances. Probably this is due to global `pub-sub` implementation?

**Comment by flekschas** [comment]
Thanks for finding and reporting this!

In theory, the two pubSub instances should be separate: https://github.com/flekschas/regl-scatterplot/blob/master/src/index.js#L79 I am not using the global pubSub instance. It could be a bug in the pubSub instance though.

I'll investigate.

**Comment by flekschas** [comment]
Oh they both fire the `select` because I am listening to a global mouse up event.

**Comment by flekschas** [comment]
Beyond the event firing, I do not notice any other leaks. Did you ran notice other glitches? A simple fix is to not fire the `select` event if the lasso was never initialized.

**Comment by flekschas** [comment]
Nevermind, there's a more serious glitch. The selection is not empty... Should have checked more carefully before replying 🤦‍♂️

**Comment by flekschas** [comment]
It should work now. This wasn't pubSub's fault. I didn't properly check when a lasso interaction started. Please test by checkout out the latest `master`, running `npm start`, and going to `http://localhost:8080/two-instances.html`.

**Comment by plankter** [comment]
Thanks you very much! It is fixed now. It looks like Issue #17 is also fixed.

**Comment by flekschas** [comment]
Thanks for battle-testing! :)
