### ISSUE TITLE
feat: Ability to pass `scaleBounds` to camera

### ISSUE THREAD

**Issue by insertmike** [flekschas/regl-scatterplot#160]
It would be very nice if we can provide `scaleBounds` argument to camera, to limit the zoom-in and out.

**Comment by flekschas** [comment]
You can set the camera's scale bounds as follows:

```js
scatterplot.get('camera').setScaleBounds([1, 10]);
```

**Comment by flekschas** [comment]
See https://github.com/flekschas/dom-2d-camera#api and https://github.com/flekschas/camera-2d#api for the camera API docs
