### ISSUE TITLE
lassoInitiator not works 

### ISSUE THREAD

**Issue by masalinas** [flekschas/regl-scatterplot#167]
I would like to active the **lassoInitiator** functionality to avoid to use the extra shift button to init the lasso functionality. I activated it one time from this piece of code. **This code is executed inside the ngAfterViewInit() function (Angular)**:

```
    this.scatterplot = createScatterplot({
      canvas,
      width,
      height
    });

    // Activate reticle and set reticle color to red and lasso initialization functionality
    this.scatterplot.set({ lassoInitiator: true, showReticle: true, reticleColor: [0, 0, 0, 0.66] });
```

As you can see I have activated this param but I need to click the shift button to initialize the lasso functinality. The showReticle works ok, but the **lassoInitiator** not. I don't know if is an issue or exist a problem from my side.

**Comment by flekschas** [comment]
Apologies! I totally missed this ticket. This is a bug. Fortunately it's easy to work around it. Simply set `lassoInitiator: true` insight the `createScatterplot` as follows:

```js
this.scatterplot = createScatterplot({
  canvas,
  width,
  height,
  lassoInitiator: true
});
```

**Comment by masalinas** [comment]
I tried to configure the scatter as you say like this:

 ```
 this.scatterplot = createScatterplot({
      canvas,
      width,
      height,
      lassoInitiator: true,
    });
```

 ```
<canvas class="canvas-points" #canvasPlot [hidden]="!hiddenSpinner"></canvas>
 ```
 
Version: "regl-scatterplot": "^1.8.5",

 But the functionality not works.

**Comment by flekschas** [comment]
How exactly do you know that the functionality is not working? I just tried it today and it works as expected for me. A short screen recording would help a lot to pin point the issue.

**Comment by flekschas** [comment]
Also as an aside, you can also lasso elements via long press if you create the scatter plot instance as follows:

```js
this.scatterplot = createScatterplot({
  canvas,
  width,
  height,
  lassoOnLongPress: true,
});
```

I personally like the long press option more as I find it less fiddly. Here's how it looks like:

![lasso long press](https://github.com/flekschas/regl-scatterplot/assets/932103/d2306356-7ebe-4314-b96a-9c5d29e0c10c)

**Comment by masalinas** [comment]
Greaye!! you were right, the atrribute to use is lassoOnLongPress: true now works ok as your video. Thanks a lot.

And taking advantage to finalize this ticket, do you now what is the configuration to show a reticle in the canvas?

regards

**Comment by flekschas** [comment]
> what is the configuration to show a reticle in the canvas?

```js
this.scatterplot = createScatterplot({
  canvas,
  width,
  height,
  lassoOnLongPress: true,
  showReticle: true,
});
```

**Comment by flekschas** [comment]
I'm closing this issue as the problem appears to be addressed.
