### ISSUE TITLE
Left clicking multiple times leads to unresponsive plot

### ISSUE THREAD

**Issue by rpadmanabhan** [flekschas/regl-scatterplot#188]
I noticed that if I click multiple times in a spot without any point it can lead to an unresponsive plot (i.e. zooming and panning has no effect). This happens when `lassoInitiator` is enabled. I can get control of the plot back if I shift and select some points. Is this something that could be fixed in the library ? 

E.g. on the demo site : 
![left_clicking_like_crazy_bug](https://github.com/user-attachments/assets/a8b7c694-cba6-4601-b0ee-53c90eba762f)

Best,
Raghav

**Comment by flekschas** [comment]
I believe what you experience is expected as clicking in an empty area triggers the lasso initiator when `lassoInitiator` is set to true. You cannot pan or zoom until either the lasso initiator disappeared or you leave it by mousing outside.

The simplest solution to this is to not use the lasso initiator and instead activate `lassoOnLongPress`

Here's how the lasso on long press works:

![lassso-on-long-press](https://github.com/user-attachments/assets/5e6a7c2a-5686-4711-9b3d-36d45a96ca69)

I noticed that the README doesn't mention the `lassoOnLongPress` at all and will update it shortly.

**Comment by rpadmanabhan** [comment]
That makes sense, thank you for that explanation.
