### ISSUE TITLE
filter() seems to change stacking of points in certain cases

### ISSUE THREAD

**Issue by rpadmanabhan** [flekschas/regl-scatterplot#197]
Hi,

I ran into a slightly unexpected behavior when filtering points. I find that in certain cases when filtering points the stacking of the points on the plot changes from what it was originally. Here is a minimal e.g.: https://codepen.io/rpadmanabhan/pen/oNKpLmj
If you uncheck Category B, i.e. the blue point, then the red point goes on top of the green one. Hitting it again calls unfilter() and that reverts back to the original stacking.
i.e. :
```
 initial stacking order: [0, 1, 2]
 action: filter index 1
 new stacking order:  [2, 0]
```

Do you have any pointers for how I could keep the same stacking order as what was initially when the plot was rendered the first time ?

Best,
Raghav

**Comment by flekschas** [comment]
That's really odd! There might be a bug in the code as to how the filtering affects the draw order of points. Thanks for reporting. I'll take a look over the weekend and next week.

**Comment by flekschas** [comment]
Apologies for the silence. The last few weeks were pretty busy. I think I found the issue. The filter function is iterating over the filtered points backwards such that invalid points can be spliced off without affecting the loop. This is neat as it means you can do `scatterplot.filter([0, 10, -2000, 2])` in your example and it'll still just display points number 0 and 2. Downside is that it inverts the stacking order 😅

Fixing this should be easy. I'm on it.

**Comment by rpadmanabhan** [comment]
Ah that makes sense, thanks for making the fix :)

**Comment by flekschas** [comment]
Turns out there's a slightly bigger leak: the inverse order in which you filter points determines the stacking of those filtered down points. 😅 Oops. Not too hard to fix either but it means regl-scatterplot will have to sort the filtered point IDs array to ensure the stacking can't be manipulated. It might take another day or two to figure out how to best implement it.

**Comment by flekschas** [comment]
Sorry it took so long but I finally got the fix ready! See https://github.com/flekschas/regl-scatterplot/pull/199
