### ISSUE TITLE
get the idices of selected points by Lasso

### ISSUE THREAD

**Issue by cherepanovic** [flekschas/regl-scatterplot#26]
it is a great scatterplot, 

may I ask some silly questions such as how can I get the indices of selected points by lasso? 

Thanks!

**Comment by flekschas** [comment]
You need to subscribe to the _select_ event as document at https://github.com/flekschas/regl-scatterplot/blob/master/README.md#scatterplot.subscribe This event will fire whenever you select point via a mouse click or the lasso. And it gives you the point indices.
