### ISSUE TITLE
draw different figures instead of points 

### ISSUE THREAD

**Issue by cherepanovic** [flekschas/regl-scatterplot#28]
Hello Fritz,

could you please point me to the position where I could extend the code for other figures (at the moment only points are possible to draw), I would like to extend it for other figures such as pies and so on. 

Thanks in advance!

**Comment by flekschas** [comment]
Unfortunately, this is not possible at the moment and I am not planning to add support for custom shapes/meshes/textures any time soon. Having said that if you're willing to flesh out a PR I am happy to integrate it (if it does not impact the general performance).

_Why only dots/points?_ Well, I created regl-scatterplot to have a interactive scatterplot that scale to millions of points. Other types of shapes are technically possible but I suspect they will harm the overall rendering and interaction performance.

_Where would I have to look to draw something other than points?_ Take a look at [`drawPoints()`](https://github.com/flekschas/regl-scatterplot/blob/master/src/index.js#L598) and the related [vertex shader](https://github.com/flekschas/regl-scatterplot/blob/master/src/point.vs). We'd need a new function (maybe called `drawMesh`) and a new vertex shaper. Additionally, for interactivity, I suspect that the [cursor/object collision check](https://github.com/flekschas/regl-scatterplot/blob/master/src/index.js#L227) needs to be updated as well.

**Comment by flekschas** [comment]
Closing this issue as I don't have any plans to address different shapes any time soon. It might come in v2.
