### ISSUE TITLE
D3 xScale domain significantly changes before and after tiny Zoom

### ISSUE THREAD

**Issue by arpitnarechania** [flekschas/regl-scatterplot#30]
@flekschas, I require some assistance w.r.t. the domain of the D3 axis scales. 

I followed the axes.js example with my data. Based on the extent of X and Y (min-max), I defined the xScale domain to [-8.57, 15.2] and the yScale domain to [-9.8, 9]. This configuration renders to:
![image](https://user-images.githubusercontent.com/2376894/98390385-4811c380-2023-11eb-94e3-50a4b4273db5.png)

**Problem #1**
The new, calculated xScale and yScale domains (after passing xScale and yScale to the scatterplot instance) are [-20, 27] and [-9.8, 9], respectively. Ok. But when I hover on any point and console.log its X and Y coordinate, it does NOT match the corresponding values on the respective axes. Why is that?

**Problem #2**
Like the demo here: https://flekschas.github.io/regl-scatterplot/axes.html, why is the rendered scatterplot **NOT** centered and constrained to the viewport extent by default?

**Problem #3** 
After performing the tiniest of Zooms, the xScale becomes [-32, 62] and yScale becomes [-9.7, 9.1]. Comparing this with the before value, yScale seems fine but there is some problem with xScale; it shifted by a significant magnitude; check the below image. Why is that?
![image](https://user-images.githubusercontent.com/2376894/98390913-fae22180-2023-11eb-9c1f-5ff7166cf90c.png)

I tried several things trying to override domains at different places but no luck. Can you help/guide?

**Comment by flekschas** [comment]
Thanks for reaching out and sorry about the issues.

> But when I hover on any point and console.log its X and Y coordinate, it does NOT match the corresponding values on the respective axes. Why is that?

The X and Y coordinates are normalized device coordinates (i.e., the webgl space). The scatterplot doesn't automatically convert those back to your data domains. You have to do this manually.

> Like the demo here: https://flekschas.github.io/regl-scatterplot/axes.html, why is the rendered scatterplot NOT centered and constrained to the viewport extent by default?
Can you elaborate a bit? It's centered and constraint for me. E.g., this is how it looks like when I open the page on my laptop.

![Uploading Screen Shot 2020-11-07 at 12.56.00 PM.png…]()

> After performing the tiniest of Zooms, the xScale becomes [-32, 62] and yScale becomes [-9.7, 9.1].

A demo would really help. It seems like there might be bug in how the xScales are computed but from just the screenshots it's hard to debug.

> I tried several things trying to override domains at different places but no luck. Can you help/guide?

You cannot override the internals of the scatterplot :) What are you trying to accomplish?

**Comment by arpitnarechania** [comment]
Hey @flekschas , I was able to solve Problem #2 above. For Problem #1 and #3, here's some more information that will help in debugging :). There is *something* that seems off.

1. In your [axes.js example](https://flekschas.github.io/regl-scatterplot/axes.html), the initial xDomain that is set in the code as well as when the app loads are [0,42]. So far so good. But, when you Zoom into the view (even if a little bit), the X-extent of points drastically changes to [0,~80]. The y-extent of points stays as is. My guess is that this is _wrong_ behaviour. You can re-create/re-experience this at your end.

2. I think the potential problem is with `width` and its internal application to the `xScale`. To confirm this, I re-created the axes.js example with 1000 points setting both the xDomain as well as yDomain to [-1,1]. Now check the below image. I started changing the width and height of the canvas. The yDomain stays as is (i.e., [-1,1]) **BUT** the xDomain changes.

![image](https://user-images.githubusercontent.com/2376894/99128468-e03a1a80-25d8-11eb-917a-24535bda7502.png)

I really hope this helps us (you) resolve the problem if any. And, to answer your question, I am using your (awesome) library to visualize a large dataset, support click, hover, lasso interaction, AND brush and link it with some more views to create a Vis system. :)

**Comment by flekschas** [comment]
Thanks for clarifying. I found the issue. It should hopefully be fixed now.

Can you pull the latest master and give regl-scatterplot a test with your data?

**Comment by arpitnarechania** [comment]
I tested with my data and it is working great, as documented. Thanks, @flekschas; you can upgrade the version. 
(I might add a few utilities and will file PRs eventually.)

**Comment by flekschas** [comment]
Sounds good! Keep the PRs coming :)
