### ISSUE TITLE
Disable the deselect event on double click in the canvas

### ISSUE THREAD

**Issue by arpitnarechania** [flekschas/regl-scatterplot#31]
How can we prevent the points from auto-deselecting when we double-click on the canvas?  Basically, I want to disable the double-click functionality.

**Comment by flekschas** [comment]
That's not possible right now but it'd be super simple to add. I suggest adding an option called `deselectOnDblClick` or something similar. By default it should be set to `true`.

Then all we have to do is check whether that option is `true` at https://github.com/flekschas/regl-scatterplot/blob/master/src/index.js#L411 before calling `deselect()`.

If you want to take a stab at it, I am happy to review your PR.

**Comment by arpitnarechania** [comment]
I will give it a shot this coming weekend, thanks.

**Comment by flekschas** [comment]
I ended up adding `deselectOnDblClick` and `deselectOnEscape` to allow disabling internal deselection. By default both props are set to `true`. You can test the code by pulling the latest master. I'll include the change in the next release once we fixed #30 :)

**Comment by arpitnarechania** [comment]
Perfect, just acknowledging that both these options work as documented.
