### ISSUE TITLE
Scatterplot disappears during panning

### ISSUE THREAD

**Issue by plankter** [flekschas/regl-scatterplot#33]
I encountered a strange behavior. In some cases (couldn't find out exact conditions yet), when background image is present and user moves an image around, the whole plot disappears. Most probably plot is destroyed as setting background image again does not help - screen stays empty. No error messages in the console.

Here is a screencast demonstrating the problem:

https://drive.google.com/file/d/16DuBjFi1c2x_t_UZF8Vg1x0g6N1Zzx0t/view

**Comment by flekschas** [comment]
Thanks for reporting and sorry about the glitch. Unfortunately, Google Drive doesn't let me play the video :( Could you maybe attach a gif showing the issue or convert the video to mp4?

Apart from that, could you setup an example demo where the same error happens? Maybe by forking https://observablehq.com/@flekschas/regl-scatterplot?

Also, do you see any error in the web dev console? My guess is that either the library runs into some exception or that the webgl context somehow died.

**Comment by plankter** [comment]
Here is an mp4 version of the screencast. No error messages were present in the console. What is strange, however, is that after today's upgrade to Chrome 87 from version 86 i cannot reproduce the issue. If it will appear again, i'll try to make a fork on observablehq.

https://drive.google.com/file/d/1GUoP37zYSj_tlMUORdWQLQqhHXNiHhaH/view?usp=sharing

**Comment by flekschas** [comment]
Thanks for updating the video. I suspect that this is caused by a broken webgl context. Unfortunately, until we have a demo where I can reproduce the error I can't fix it.

**Comment by flekschas** [comment]
Is this still an issue?

**Comment by plankter** [comment]
I cannot reproduce it anymore. I'll reopen the ticket if it'll happen again.
