### ISSUE TITLE
babel dependency problems 

### ISSUE THREAD

**Issue by cherepanovic** [flekschas/regl-scatterplot#39]
Hello Flekschas,

I am struggling with the integration of your lib, unfortunately, I am struggling with babel dependencies. 

Maybe you could give me an advice 

```
./node_modules/regl-scatterplot/dist/regl-scatterplot.esm.js 3157:9
Module parse failed: Unexpected token (3157:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   } = initialProperties;
|   checkReglExtensions(regl);
>   regl ||= createRegl(canvas);
|   backgroundColor = toRgba(backgroundColor, true);
|   lassoColor = toRgba(lassoColor, true);
```

**Comment by flekschas** [comment]
Oh, yeah this is a new language feature: [logical assignment operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment). You need the following plugin for babel to handle it: https://github.com/flekschas/regl-scatterplot#L9

Maybe I should have not added this feature. Seem a bit too much on the bleeding edge.

**Comment by cherepanovic** [comment]
I installed all babel packages which you also have in [https://github.com/flekschas/regl-scatterplot/blob/master/.babelrc](here).

Unfortunately, it did not work for me... I don't know why... 

I changed provisionally `regl ||= createRegl(canvas);` into 

```
  if(regl == null){
    regl = createRegl(canvas);
  }
```

I have to thank you for your support!

**Comment by flekschas** [comment]
Just to double check, did you also activate the plugins? Just installing them via npm isn't enough. You would have to add them to your local `.babelrc` file or wherever you configure babel.

I will revert the change in a future release. `regl ||= createRegl(canvas);` is the same as `regl = regl || createRegl(canvas);` (it's just shorter and more elegant, in my mind, which is why I added it)

**Comment by cherepanovic** [comment]
>Just to double check, did you also activate the plugins?

is in my config.json, but I will make sure how to activate them properly

Thank you! 

I would close the issue since you clarified everything

**Comment by flekschas** [comment]
Mhh it's odd it doesn't work.

I'll reopen the issue just so I don't forget to switch back to the regular operators. There shouldn't be a need to install special babel plugins :)

**Comment by flekschas** [comment]
The next version of regl-scatterplot (v0.17) gets of the dependency on babel's logical assignment operator plugin. So hopefully everything works again as before.

Thanks for bringing this to my attention!

**Comment by bryan-d** [comment]
FYI, getting this error again here:

```
frontend_1  |   5849 |       data[k + 2] = z; // z: value 1
frontend_1  |   5850 |       data[k + 3] = w; // w: value 2
frontend_1  | > 5851 |       zIsInts &&= Number.isInteger(z);
frontend_1  |        |               ^
frontend_1  |   5852 |       wIsInts &&= Number.isInteger(w);
frontend_1  |   5853 |     }
frontend_1  |   5854 |
```
