### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by japrescott** [flekschas/regl-scatterplot#43]
hey @flekschas!
Great library! I was wondering if you already have some typescript definitions lying around? Otherwise I will try and write some
Thank you and have a great week

**Comment by flekschas** [comment]
Unfortunately I don't because I don't use typescript much. If you can take a stab at that, that''d be much appreciated!

**Comment by joaorulff** [comment]
Hello, 

I'm having the following problem when trying to import regl. Could you help?

`Could not find a declaration file for module 'camera-2d-simple'.`

**Comment by flekschas** [comment]
@joaorulff Your issue seems unrelated to typescript definitions. Could you open a new issue and provide more context?
