### ISSUE TITLE
Check browser support

### ISSUE THREAD

**Issue by flekschas** [flekschas/regl-scatterplot#45]
It seems like in some versions of Safari (v14) the library doesn't render the points properly. Since it's rendering in Safari v13 it might have to do with the webgl extensions that are required.

**Comment by flekschas** [comment]
Thanks to @sehilyi I now know that the only browsers that has issues rendering the scatter plot is Safari v14. Safari v13 works fine.

Below is the error shown in Safari v14:

![Screen Shot 2021-04-08 at 10 58 10 PM](https://user-images.githubusercontent.com/932103/114188050-b500f080-9916-11eb-8ddc-180c67b54203.png)

**Comment by flekschas** [comment]
I can confirm the library also works in Safari v13.1.2. So it's only v14 that's messed up. Congrats Apple!

**Comment by japrescott** [comment]
do you have an idea to why this is happening? I didn't find any issues in `regl` itself. Does it have to do with the opacity? The shader?

**Comment by japrescott** [comment]
if you point me in the "right direction" (file, line) I will try and help to debug things for you. What do you mean by the `state texture`?

**Comment by flekschas** [comment]
I am referring to [`createStateTexture()`](https://github.com/flekschas/regl-scatterplot/blob/master/src/index.js#L1525).

regl-scatterplot uses a texture object to store information about the points.

**Comment by flekschas** [comment]
After updating my OS I found the issue. It's somehow related to updating the frame buffer:

```js
fbo.resize(...fboRes);
```

**Comment by flekschas** [comment]
Getting closer! It seems to be related to the color blending. When I turn that off, I at least see the dots in Safari.

When `performanceMode: true` the scatter plot works as expected in Safari as well.

**Comment by flekschas** [comment]
Alright, it's related to alpha blending! I was able to recreate it in a jsFiddle. Line 89 is what Safari is not able to handle...

https://jsfiddle.net/flek/rc6zbk0d/52/

As soon as blending is enabled, the plot is empty.

To test if this was related to the primitive, I've added a translucent triangle. But it seems to be a general problem.

**Comment by flekschas** [comment]
Alright it's even more crazy. The issue isn't the blend function alone. It's the blend function in combination with framebuffer rendering which does not work in Safari 14.

**Demo**: https://jsfiddle.net/flek/rc6zbk0d/58/

It _should_ look as follows:
![May-21-2021 17-57-29](https://user-images.githubusercontent.com/932103/119203332-c8988e80-ba60-11eb-86a1-baae8157e872.gif)

However, in Safari 14 the _purple triangle+dots are never rendered_.

**Comment by japrescott** [comment]
great work investigating! Grosses Kino! I was not able to get past why `fbo.resize(...fboRes);` was failing. Awesome you were able to pinpoint it that well. 🥳
