### ISSUE TITLE
double-precision data is plotted well with regard to resolution?

### ISSUE THREAD

**Issue by kkdd** [flekschas/regl-scatterplot#49]
Hello,
Is double-precision data such as below plotted well with regard to resolution in regl-scatterplot?

```
data = [[1.0, 1.00000000000], [1.0, 1.00000000001], [1.0, 1.00000000002]]
```

**Comment by flekschas** [comment]
Have you tried it? And how do you define "well plotted"?

**Comment by kkdd** [comment]
Thank you for comment.
The following is the result by using ```testData = [[0.00000000, 1.00000000], [0.00000001, 1.00000001], [0.00000002, 1.00000002]]```, which is plotted as if ```1.00000000=1.00000001=1.00000002```:

![regl-scatterplot](https://user-images.githubusercontent.com/5372642/114888974-aa79b600-9e44-11eb-98e7-38832dea5eb7.jpg)

**Comment by flekschas** [comment]
Yep. Float64 textures are not supported in WebGL as far as I know.

For more details see https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices (in particular "ESSL100 minimum requirements (WebGL 1)").
