### ISSUE TITLE
Allow columnar 1D (Typed)Arrays in `plot.draw`

### ISSUE THREAD

**Issue by manzt** [flekschas/regl-scatterplot#59]
re: https://github.com/flekschas/jupyter-scatter/pull/11#issue-670585031

### Motivation

`regl-scatterplot` requires data to be nested 2D JavaScript Array of entries (`[[x0, y0, ...], [x1, y1, ...], ...]`. It would be nice to have an API exposed to pass _columnar_ arrays for each field.

```javascript
plot.draw({
  x: new Float32Array([x0, x1, ...]),
  y: new Float32Array([y0, y1, ...]),
  // ...
});
```

This way the visual encodings can be named explicitly, and `regl-scatterplot` will be a good match for data that are columnar in nature (e.g. Apache Arrow).

EDIT: Maybe some useful information - https://observablehq.com/@mbostock/manipulating-flat-arrays

**Comment by flekschas** [comment]
One caveat: we will always need classic row-based arrays as regl-scatterplot relies on [KDBush](https://github.com/mourner/kdbush) for indexing points. Row-based arrays can directly be passed into KDBush without requiring any conversion. For convenience, columnar array support would be nice but I doubt it will have any impact on the overall performance.
