### ISSUE TITLE
[feature] drawing lines

### ISSUE THREAD

**Issue by kkdd** [flekschas/regl-scatterplot#6]
Hello,
Can I draw lines (or gridlines) on a regl-scatterplot? Can I use regl-scatterplot and regl-line together?

**Comment by flekschas** [comment]
Could you provide a specific example/use case? Out of the box, regl-scatterplot doesn't support gridlines but you can, for example, use a gridline image as the background for regl-scatterplot.

Checkout this example: https://github.com/flekschas/regl-scatterplot/blob/master/example/texture-background.js

You can, of course, render anything you like into a regl texture object and pass that to regl-scatterplot via the constructor (e.g., `createScatterplot({ backgroundImage }}`) or via the `set` function (e.g., `set({ backgroundImage})`)

**Comment by kkdd** [comment]
Thank you for your suggestion.
I would like to draw and microscopically zoom a scatter plot of a million of points with gridlines, like as [color_scatter](http://docs.bokeh.org/en/1.4.0/docs/gallery/color_scatter.html) and [Accelerating with WebGL](https://docs.bokeh.org/en/1.4.0/docs/user_guide/webgl.html) in [Bokeh](https://bokeh.org/) gallery and examples. (I regret to say, however, that Bokeh doesn't seem to achieve full performance of WebGL for plotting points as of now.)

**Comment by flekschas** [comment]
For the gridlines, I think creating the background image yourself is really the best option. I am also happy to merge that feature if you come up with a flexible solution.

The only thing we might have to add is an option to re-render the background image upon zooming in such that the resolution can be updated. Otherwise, the gridlines would become gigantic if you zoom in a lot.

**Comment by flekschas** [comment]
Not sure if this is still relevant but with the recent changes related to #29 is fairly simple to draw a grid using [d3-axes]().

The only addition to [examples/axes.js]() is that you need to insert the following two lines of code at line 51:

```javascript
xAxis.tickSizeInner(-height);
yAxis.tickSizeInner(-width);
```

It'll look as follows:

![Oct-07-2020 17-59-49](https://user-images.githubusercontent.com/932103/95356435-f3194b00-08c6-11eb-83b3-4240c4f0e992.gif)

**Comment by flekschas** [comment]
If this is not sufficient please reopen the ticket.
