### ISSUE TITLE
release? :)

### ISSUE THREAD

**Issue by japrescott** [flekschas/regl-scatterplot#63]
hey @flekschas looks awesome what you were able to do together with @manzt. Great work! I was just wondering when you were planing on pushing a new release?

**Comment by flekschas** [comment]
I am currently out of the office but a new release will come out soon.

**Comment by japrescott** [comment]
thanks a lot for releasing and thanks again for this awesome lib :)

**Comment by flekschas** [comment]
You're welcome! Thanks for using and supporting the library 🙇
