### ISSUE TITLE
Is it possible to get points in current view?

### ISSUE THREAD

**Issue by dulex123** [flekschas/regl-scatterplot#72]
Can I somehow get points in current view? I would like to draw text on top of every point in a particular zoom level

**Comment by flekschas** [comment]
It's currently not possible. However, it's trivial to add and sounds like a useful feature in general. Hence, I'll add a function for this in the coming days (as free time permits)

**Comment by dulex123** [comment]
@flekschas would it go something like get current view and get all dots within range? 2d sort ? Or is it smth even more simpler i could send a pr

**Comment by flekschas** [comment]
It's very simple as all the ingredients are already in place:
- get the gl coordinates of the top-left, top-right, bottom-left, and bottom-right corner of the canvas element
- query the `searchIndex` for all the points within those four coordinates

I imagine the API to be called something like `scatterplot.getPointsInView()`. You can then use the existing `view` event to listen to changes of the view.

**Comment by dulex123** [comment]
@flekschas Thanks. Any hints to which files i can look at? Webgl is new to me but I would like to take a go at it

**Comment by dulex123** [comment]
@flekschas This seems to work. https://github.com/flekschas/regl-scatterplot/pull/73 

Can I somehow get absolute (browser) coordinates of points so I can create some DOM elements over them?

**Comment by flekschas** [comment]
Yes, you have to get the model, view, and projection matrices. (See `getProjectionViewModel()`) The resulting matrix can be used to translate normalized device coords (the point coordinates) into screen coords via
```js
const out = vec4.transformMat4([], [pointGlX, pointGlY, 1, 1], getProjectionViewModel());
// out[0] and out[1] should be the x and y coords relative to your canvas element
```
Let me know if this works. Otherwise I can test this later as well

**Comment by flekschas** [comment]
Here's how you can get the screen coords for points

```js
import { scaleLinear } from 'd3-scale';

const points = Array.from({ length: 100 }, () => [
  -1 + Math.random() * 2, // x
  -1 + Math.random() * 2, // y
]);

// Points are in normalized device coordinates [-1, 1]
const xScale = scaleLinear().domain([-1, 1]);
const yScale = scaleLinear().domain([-1, 1]);

const scatterplot = createScatterplot({
 ...,
  xScale,
  yScale,
});

scatterplot.draw(points);

scatterplot.subscribe('view', ({ xScale, yScale }) => {
  const pointsInView = scatterplot.get('pointsInView');
  const pointScreenCoords = pointsInView.map((pointId) => [
    xScale(points[pointId][0]),
    yScale(points[pointId][1]),
  ]);
  console.log('points in view', pointScreenCoords);
});
```

**Comment by flekschas** [comment]
New version with `scatterplot.get('pointsInView');` is out!

Also, I pieced together a demo for showing how to overlay labels: https://flekschas.github.io/regl-scatterplot/text-labels.html

Thanks again for bringing this up and taking a stab at it!
