### ISSUE TITLE
D3 scale linking only works with continuous scales

### ISSUE THREAD

**Issue by e-katzenstein** [flekschas/regl-scatterplot#91]
As mentioned here: https://github.com/flekschas/regl-scatterplot#synchronize-d3-x-and-y-scales-with-the-scatterplot-view

The source code shows that the scale only works with ScaleContinuousNumeric, but should also work with time and ordinal scales.

**Comment by flekschas** [comment]
This is not a bug but simply a feature that's not support unfortunately.

Discontinuous scales are not supported and there's no concrete plan to add support any time soon.

Temporal scales are supported if time is represented numerically. (e.g., in msec from 1970 as provided by `Date.now()`).
