### ISSUE TITLE
Disable zoom and pan

### ISSUE THREAD

**Issue by e-katzenstein** [flekschas/regl-scatterplot#94]
Is there a way to disable zoom and pan? Can't find this in the documentation or the source code.

**Comment by e-katzenstein** [comment]
This is working for me (reference camera from dom-2d-camera library):

`scatterplot.get('camera').config({ isFixed: true })`

**Comment by flekschas** [comment]
Yep, by fixing the camera one can disable pan & zoom. There isn't any extra/custom API in regl-scatterplot.
